In [1]:
import pandas as pd

In [2]:
df_train=pd.read_csv('train.csv')
df_train.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df_test=pd.read_csv('test.csv')
df_test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
print(df_train.shape)
print(df_test.shape)

(42000, 785)
(28000, 784)

In [5]:
X_train  = df_train.iloc[:, 1:].values
y_train = df_train.iloc[:, 0].values
X_test=df_test

In [6]:
X_train = X_train/255.0
X_test = X_test/255.0

In [8]:
import numpy as np
from NN_Numpy import LinearLayer, ReLU, CrossEntropyLoss, SGD, Model

num_classes = 10
y_train_onehot = np.eye(num_classes)[y_train]

model = Model()
model.add_layer(LinearLayer(784, 128))
model.add_layer(ReLU())
model.add_layer(LinearLayer(128, 64))
model.add_layer(ReLU())
model.add_layer(LinearLayer(64, 10))

loss_fn = CrossEntropyLoss()
optimizer = SGD(lr=0.1) 
model.compile(loss_fn, optimizer)

model.train(X_train, y_train_onehot, epochs=50, batch_size=32)

print("\nEvaluation on Training Data:")
train_loss, train_acc = model.evaluate(X_train, y_train_onehot)
print(f"Final Training Accuracy: {train_acc:.2%}")

Epoch 1/50 - Loss: 1.0324
Epoch 2/50 - Loss: 0.2306
Epoch 3/50 - Loss: 0.1418
Epoch 4/50 - Loss: 0.1048
Epoch 5/50 - Loss: 0.0806
Epoch 6/50 - Loss: 0.0676
Epoch 7/50 - Loss: 0.0539
Epoch 8/50 - Loss: 0.0435
Epoch 9/50 - Loss: 0.0355
Epoch 10/50 - Loss: 0.0283
Epoch 11/50 - Loss: 0.0236
Epoch 12/50 - Loss: 0.0195
Epoch 13/50 - Loss: 0.0172
Epoch 14/50 - Loss: 0.0151
Epoch 15/50 - Loss: 0.0108
Epoch 16/50 - Loss: 0.0091
Epoch 17/50 - Loss: 0.0071
Epoch 18/50 - Loss: 0.0037
Epoch 19/50 - Loss: 0.0026
Epoch 20/50 - Loss: 0.0017
Epoch 21/50 - Loss: 0.0013
Epoch 22/50 - Loss: 0.0010
Epoch 23/50 - Loss: 0.0009
Epoch 24/50 - Loss: 0.0008
Epoch 25/50 - Loss: 0.0007
Epoch 26/50 - Loss: 0.0006
Epoch 27/50 - Loss: 0.0006
Epoch 28/50 - Loss: 0.0005
Epoch 29/50 - Loss: 0.0005
Epoch 30/50 - Loss: 0.0004
Epoch 31/50 - Loss: 0.0004
Epoch 32/50 - Loss: 0.0004
Epoch 33/50 - Loss: 0.0004
Epoch 34/50 - Loss: 0.0004
Epoch 35/50 - Loss: 0.0003
Epoch 36/50 - Loss: 0.0003
Epoch 37/50 - Loss: 0.0003
Epoch 38/50 - Loss: 0.0003
Epoch 39/50 - Loss: 0.0003
Epoch 40/50 - Loss: 0.0003
Epoch 41/50 - Loss: 0.0003
Epoch 42/50 - Loss: 0.0003
Epoch 43/50 - Loss: 0.0002
Epoch 44/50 - Loss: 0.0002
Epoch 45/50 - Loss: 0.0002
Epoch 46/50 - Loss: 0.0002
Epoch 47/50 - Loss: 0.0002
Epoch 48/50 - Loss: 0.0002
Epoch 49/50 - Loss: 0.0002
Epoch 50/50 - Loss: 0.0002

Evaluation on Training Data:
Evaluation -> Loss: 0.0002, Accuracy: 100.00%
Final Training Accuracy: 100.00%

In [9]:
if hasattr(X_test, 'values'):
    X_test_np = X_test.values
else:
    X_test_np = X_test

logits = model.predict(X_test_np)

predicted_labels = np.argmax(logits, axis=1)

submission = pd.DataFrame({
    'ImageId': np.arange(1, len(predicted_labels) + 1),
    'Label': predicted_labels
})

submission.to_csv('submission.csv', index=False)
print("'submission.csv' saved")
print(submission.head())

Success! 'submission.csv' saved. First 5 rows:
   ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3